### ISSUE TITLE
Add support for postgres persistence 

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-transaction-manager#21]

**Comment by peterbroadhurst** [comment]
Dropping some thoughts on this issue, and assigning over to @matthew1001 for the next step.

https://github.com/hyperledger/firefly-common/pull/39 was a big pre-req step to enabling this issue to be built efficiently:
- Pulls the Filter API capabilities out of Core, so it can be re-used for _defining_ rich filter APIs
- Pulls the SQL scaffolding code out of Core, so it can be re-used for _implementing_ the SQL leg of the persistence

However, there are some extra challenges for FFTM because it already has a persistence implementation - that's very lightweight and convenient based on LevelDB... with the following challenges:
- There's an existing API for query that doesn't strictly abide to the FF Filter syntax
- LevelDB is never going to support the full range of filters in the FF Filter syntax

So my line of thinking, as I had this over to you @matthew1001 to take it forwards is:
1. Refactor https://github.com/hyperledger/firefly-transaction-manager/blob/main/internal/persistence/persistence.go into a pluggable `persistence` interface, just like https://github.com/hyperledger/firefly/blob/main/pkg/database/plugin.go
2. Update the API to use the `FilterFactory`/`FilterResult` helpers to generate a fully documented rich query API
3. Implement and test this in SQL using https://github.com/hyperledger/firefly/tree/main/internal/database/sqlcommon as the reference
    - The SQL version will be fully featured in terms of filtering, due to all the helpers that already exist
    - This will mean building migrations of PostgreSQL
4. There's now two options:
    a. Do a minimal 2nd plugin implementation that maps this new API/code interface down to the existing LevelDB data structures
        - This is more code work in the FFTM codebase, but avoids migration
    b. Build a set of SQLite migrations, and a procedure/script/code that allows users to migrate the old LevelDB data structures into SQLite.
        - SQLite gives similar convenience for local CLI environments as LevelDB, but wouldn't really be valid for use in any kind of production scenario (whereas it could be argued that LevelDB is a valid alternative in some cases)

**Comment by matthew1001** [comment]
Thanks for those initial thoughts, really useful. I'll start looking at this and which FFTM release we might be able to get it in to.
